version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./.env
    restart: "always" # Update restart policy if needed
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
