FRAME_WIDTH=640
FRAME_HEIGHT=480
THRESHOLD_SIMILARITY=0.9

BATCH_SIZE=32

VIDEO_FOLDER=r'C:\AIC-2024-DATA\videos'
FRAME_FOLDER = r'C:\AIC-2024-DATA\frames'
KEYFRAME_FOLDER = r'C:\AIC-2024-DATA\keyframes'
EMBEDDING_FOLDER = r'C:\AIC-2024-DATA\embeddings'
OBJECTS_FOLDER = r'C:\AIC-2024-DATA\objects'


