version: "3.8"
services:
  ai:
    build: 
      context: ../ai
      dockerfile: Dockerfile
    container_name: ai
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ../ai
        target: /ai
      - type: bind
        source: ${VIDEOS_PATH}
        target: ${VIDEOS_VOLUME_DIR}
      - type: bind
        source: ${FRAMES_PATH}
        target: ${FRAMES_VOLUME_DIR}
      - type: bind
        source: ${KEYFRAME_FOLDER}
        target: ${KEYFRAME_VOLUME_DIR}
      - type: bind
        source: ${EMBEDDING_FOLDER}
        target: ${EMBEDDING_VOLUME_DIR}
      - type: bind
        source: ${MODELS_FOLDER}
        target: ${MODELS_VOLUME_DIR}
      - type: bind
        source: ${OBJECTS_FOLDER}
        target: ${OBJECTS_VOLUME_DIR}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
